name: Terraform Security Scan

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - "feature/**"
      - "feat/**"
      - "fix/**"
      - "wip/**"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  tfsec:
    name: TFSec Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan Terraform with tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: .
          version: v1.28.14
          additional_args: --minimum-severity HIGH --no-color
          github_token: ${{ secrets.GITHUB_TOKEN }}